#pragma once
#include "../../sdl/SDLUtils.h"
#include "../../deps/nlohmann/json.hpp"

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SDL_Point, x, y)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SDL_FPoint, x, y)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SDL_Rect, x, y, w, h)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SDL_FRect, x, y, w, h)

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SDL_Color, r, g, b, a)

NLOHMANN_JSON_SERIALIZE_ENUM(
	SDL_RendererFlip,
	{
		{ SDL_RendererFlip::SDL_FLIP_NONE,		 "SDL_FLIP_NONE"	   },
		{ SDL_RendererFlip::SDL_FLIP_HORIZONTAL, "SDL_FLIP_HORIZONTAL" },
		{ SDL_RendererFlip::SDL_FLIP_VERTICAL,   "SDL_FLIP_VERTICAL"   }
	}
)

NLOHMANN_JSON_SERIALIZE_ENUM(
	SDL_BlendMode,
	{
		{ SDL_BlendMode::SDL_BLENDMODE_NONE,	"SDL_FLIP_NONE"			},
		{ SDL_BlendMode::SDL_BLENDMODE_BLEND,   "SDL_BLENDMODE_BLEND"	},
		{ SDL_BlendMode::SDL_BLENDMODE_ADD,     "SDL_BLENDMODE_ADD"		},
		{ SDL_BlendMode::SDL_BLENDMODE_MOD,     "SDL_BLENDMODE_MOD"		},
		{ SDL_BlendMode::SDL_BLENDMODE_MUL,     "SDL_BLENDMODE_MUL"		},
		{ SDL_BlendMode::SDL_BLENDMODE_INVALID, "SDL_BLENDMODE_INVALID" }
	}
)